config/routes.rb
Rails.application.routes.draw do
  resources :rides, only: [:create, :new, :index] do
    resources :reservations, only: [:create]
  end

  resources :bus_rides, only: [] do
    resources :reservations, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus_ride.rb
class BusRide < Ride
  validates :price, numericality: { greater_than: 0 }

  def self.default_scope
    where(vehicle_type: "bus")
  end

  def price_in_dollars=(new_price)
    write_attribute(:price_in_cents, new_price.to_f * 100.0)
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :ride
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  has_many :reservations

  validates :seats, numericality: { greater_than: 0 }

  def self.default_scope
    where(vehicle_type: "car")
  end

  def has_available_seats?
    available_seats > 0
  end

  def available_seats
    seats - reservations.count
  end

  def price_in_dollars=(new_price)
    write_attribute(:price_in_cents, new_price.to_f * 100.0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def create
    ride = Ride.find(params[:ride_id])
    reservation = Reservation.new(ride: ride)
    if reservation.save
      flash[:success] = "Your seat has been reserved"
    else
      flash[:error] = "There was a problem creating your reservation"
    end
    redirect_to rides_path
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  def create
    @ride = Ride.new(ride_params)
    if @ride.save
      flash[:success] = "Ride created succesfully"
      redirect_to rides_path
    else
      render :new
    end
  end

  def index
    @rides = CombinedRidesQuery.new.rides
  end

  def new
    @ride = RidePresenter.new(Ride.new, ActionView::Base.new)
  end

  private

  def ride_params
    params.require(:ride).permit(:destination, :origin, :seats, :vehicle_type, :price_in_dollars)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def present(object, klass=nil)
    klass ||= "#{object.class}Presenter".constantize
    presenter = klass.new(object, self)
    yield presenter
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/bus_rides/_bus_ride.html.erb
<div class="ride">
  <dl>
    <dt>Destination:</dt>
    <dd>
      <%= bus_ride.destination %>
    </dd>
    <dt>Origin:</dt>
    <dd>
      <%= bus_ride.origin %>
    </dd>
    <dt>Seats:</dt>
    <dd>
      <%= bus_ride.seats %>
    </dd>
    <dt>Seats Left:</dt>
    <dd>
      <%= bus_ride.available_seats %>
    </dd>
    <dt>Price:</dt>
    <dd>
      <%= bus_ride.price_in_humanized_dollars %>
    </dd>
  </dl>
  <span class="badge-notice">Sponsored Bus Ride</span>
  <%= bus_ride.reserve_button %>
</div>

app/views/bus_rides/_disabled_reserve_button.html.erb
Ride Full

app/views/bus_rides/_reserve_button.html.erb
<%= link_to bus_ride_reservations_path(ride), method: "POST", class: "reserve button" do %>
  Reserve a seat
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "flashes" -%>
  <div class="container">
    <%= yield %>
    <%= render "javascript" %>
    <%= render "css_overrides" %>
  </div>
</body>
</html>

app/views/pages/home.html.erb
Transporter 2

<%= link_to "Rides", rides_path %>

app/views/refills/_badges.html.erb
<div>
  <span class="badge">4</span>
  <span class="badge-alert">4</span>
  <span class="badge-error">4</span>
  <span class="badge-notice">4</span>
  <span class="badge-success">4</span>
</div>

app/views/rides/_bus.html.erb
<div class="ride">
  <dl>
    <dt>Destination:</dt>
    <dd>
      <%= bus.destination %>
    </dd>
    <dt>Origin:</dt>
    <dd>
      <%= bus.origin %>
    </dd>
    <dt>Seats:</dt>
    <dd>
      <%= bus.seats %>
    </dd>
    <dt>Seats Left:</dt>
    <dd>
      <%= bus.available_seats %>
    </dd>
    <dt>Price:</dt>
    <dd>
      <%= bus.price_in_humanized_dollars %>
    </dd>
  </dl>
  <%= bus.reserve_button %>
</div>

app/views/rides/_reserve_button.html.erb
<%= link_to ride_reservations_path(ride), method: "POST", class: "reserve button" do %>
  Reserve a seat
<% end %>

app/views/rides/_ride.html.erb
<div class="ride">
  <div class="ride-details">
    <dl>
      <dt>Destination:</dt>
      <dd>
        <%= ride.destination %>
      </dd>
      <dt>Origin:</dt>
      <dd>
        <%= ride.origin %>
      </dd>
      <dt>Seats:</dt>
      <dd>
        <%= ride.seats %>
      </dd>
      <dt>Seats Left:</dt>
      <dd>
        <%= ride.available_seats %>
      </dd>
      <dt>Price:</dt>
      <dd>
        <%= ride.price_in_humanized_dollars %>
      </dd>
    </dl>
  </div>
  <%= ride.reserve_button %>
</div>

app/views/rides/index.html.erb
<h1>Rides</h1>
<%= link_to "New Ride", new_ride_path %>
<%- @rides.each do |_ride| %>
  <%- present(_ride) do |ride| %>
    <%= render ride %>
  <% end %>
<% end %>

app/views/rides/new.html.erb
<%= simple_form_for @ride do |f| %>
  <%= f.input :vehicle_type, collection: @ride.vehicle_types, label_method: :titleize %>
  <%= f.input :destination %>
  <%= f.input :origin %>
  <%= f.input :seats %>
  <%= f.input :price_in_dollars %>

  <%= f.submit "Create Ride" %>
<% end %>